<?php

namespace Database\Seeders\Address;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::insert([
            ['id' => '1', 'title' => 'afghanistan', "code" => "code"],
            ['id' => '2', 'title' => 'albania', "code" => "code"],
            ['id' => '3', 'title' => 'algeria', "code" => "code"],
            ['id' => '4', 'title' => 'american samoa', "code" => "code"],
            ['id' => '5', 'title' => 'andorra', "code" => "code"],
            ['id' => '6', 'title' => 'angola', "code" => "code"],
            ['id' => '7', 'title' => 'anguilla', "code" => "code"],
            ['id' => '8', 'title' => 'antarctica', "code" => "code"],
            ['id' => '9', 'title' => 'antigua and barbuda', "code" => "code"],
            ['id' => '10', 'title' => 'argentina', "code" => "code"],
            ['id' => '11', 'title' => 'armenia', "code" => "code"],
            ['id' => '12', 'title' => 'aruba', "code" => "code"],
            ['id' => '13', 'title' => 'australia', "code" => "code"],
            ['id' => '14', 'title' => 'austria', "code" => "code"],
            ['id' => '15', 'title' => 'azerbaijan', "code" => "code"],
            ['id' => '16', 'title' => 'bahamas the', "code" => "code"],
            ['id' => '17', 'title' => 'bahrain', "code" => "code"],
            ['id' => '18', 'title' => 'bangladesh', "code" => "code"],
            ['id' => '19', 'title' => 'barbados', "code" => "code"],
            ['id' => '20', 'title' => 'belarus', "code" => "code"],
            ['id' => '21', 'title' => 'belgium', "code" => "code"],
            ['id' => '22', 'title' => 'belize', "code" => "code"],
            ['id' => '23', 'title' => 'benin', "code" => "code"],
            ['id' => '24', 'title' => 'bermuda', "code" => "code"],
            ['id' => '25', 'title' => 'bhutan', "code" => "code"],
            ['id' => '26', 'title' => 'bolivia', "code" => "code"],
            ['id' => '27', 'title' => 'bosnia and herzegovina', "code" => "code"],
            ['id' => '28', 'title' => 'botswana', "code" => "code"],
            ['id' => '29', 'title' => 'bouvet island', "code" => "code"],
            ['id' => '30', 'title' => 'brazil', "code" => "code"],
            ['id' => '31', 'title' => 'british indian ocean territory', "code" => "code"],
            ['id' => '32', 'title' => 'brunei', "code" => "code"],
            ['id' => '33', 'title' => 'bulgaria', "code" => "code"],
            ['id' => '34', 'title' => 'burkina faso', "code" => "code"],
            ['id' => '35', 'title' => 'burundi', "code" => "code"],
            ['id' => '36', 'title' => 'cambodia', "code" => "code"],
            ['id' => '37', 'title' => 'cameroon', "code" => "code"],
            ['id' => '38', 'title' => 'canada', "code" => "code"],
            ['id' => '39', 'title' => 'cape verde', "code" => "code"],
            ['id' => '40', 'title' => 'cayman islands', "code" => "code"],
            ['id' => '41', 'title' => 'central african republic', "code" => "code"],
            ['id' => '42', 'title' => 'chad', "code" => "code"],
            ['id' => '43', 'title' => 'chile', "code" => "code"],
            ['id' => '44', 'title' => 'china', "code" => "code"],
            ['id' => '45', 'title' => 'christmas island', "code" => "code"],
            ['id' => '46', 'title' => 'cocos (keeling) islands', "code" => "code"],
            ['id' => '47', 'title' => 'colombia', "code" => "code"],
            ['id' => '48', 'title' => 'comoros', "code" => "code"],
            ['id' => '49', 'title' => 'congo', "code" => "code"],
            ['id' => '50', 'title' => 'congo the democratic republic of the', "code" => "code"],
            ['id' => '51', 'title' => 'cook islands', "code" => "code"],
            ['id' => '52', 'title' => 'costa rica', "code" => "code"],
            ['id' => '53', 'title' => 'cote d\'ivoire (ivory coast)', "code" => "code"],
            ['id' => '54', 'title' => 'croatia (hrvatska)', "code" => "code"],
            ['id' => '55', 'title' => 'cuba', "code" => "code"],
            ['id' => '56', 'title' => 'cyprus', "code" => "code"],
            ['id' => '57', 'title' => 'czech republic', "code" => "code"],
            ['id' => '58', 'title' => 'denmark', "code" => "code"],
            ['id' => '59', 'title' => 'djibouti', "code" => "code"],
            ['id' => '60', 'title' => 'dominica', "code" => "code"],
            ['id' => '61', 'title' => 'dominican republic', "code" => "code"],
            ['id' => '62', 'title' => 'east timor', "code" => "code"],
            ['id' => '63', 'title' => 'ecuador', "code" => "code"],
            ['id' => '64', 'title' => 'egypt', "code" => "code"],
            ['id' => '65', 'title' => 'el salvador', "code" => "code"],
            ['id' => '66', 'title' => 'equatorial guinea', "code" => "code"],
            ['id' => '67', 'title' => 'eritrea', "code" => "code"],
            ['id' => '68', 'title' => 'estonia', "code" => "code"],
            ['id' => '69', 'title' => 'ethiopia', "code" => "code"],
            ['id' => '70', 'title' => 'external territories of australia', "code" => "code"],
            ['id' => '71', 'title' => 'falkland islands', "code" => "code"],
            ['id' => '72', 'title' => 'faroe islands', "code" => "code"],
            ['id' => '73', 'title' => 'fiji islands', "code" => "code"],
            ['id' => '74', 'title' => 'finland', "code" => "code"],
            ['id' => '75', 'title' => 'france', "code" => "code"],
            ['id' => '76', 'title' => 'french guiana', "code" => "code"],
            ['id' => '77', 'title' => 'french polynesia', "code" => "code"],
            ['id' => '78', 'title' => 'french southern territories', "code" => "code"],
            ['id' => '79', 'title' => 'gabon', "code" => "code"],
            ['id' => '80', 'title' => 'gambia the', "code" => "code"],
            ['id' => '81', 'title' => 'georgia', "code" => "code"],
            ['id' => '82', 'title' => 'germany', "code" => "code"],
            ['id' => '83', 'title' => 'ghana', "code" => "code"],
            ['id' => '84', 'title' => 'gibraltar', "code" => "code"],
            ['id' => '85', 'title' => 'greece', "code" => "code"],
            ['id' => '86', 'title' => 'greenland', "code" => "code"],
            ['id' => '87', 'title' => 'grenada', "code" => "code"],
            ['id' => '88', 'title' => 'guadeloupe', "code" => "code"],
            ['id' => '89', 'title' => 'guam', "code" => "code"],
            ['id' => '90', 'title' => 'guatemala', "code" => "code"],
            ['id' => '91', 'title' => 'guernsey and alderney', "code" => "code"],
            ['id' => '92', 'title' => 'guinea', "code" => "code"],
            ['id' => '93', 'title' => 'guinea-bissau', "code" => "code"],
            ['id' => '94', 'title' => 'guyana', "code" => "code"],
            ['id' => '95', 'title' => 'haiti', "code" => "code"],
            ['id' => '96', 'title' => 'heard and mcdonald islands', "code" => "code"],
            ['id' => '97', 'title' => 'honduras', "code" => "code"],
            ['id' => '98', 'title' => 'hong kong s.a.r.', "code" => "code"],
            ['id' => '99', 'title' => 'hungary', "code" => "code"],
            ['id' => '100', 'title' => 'iceland', "code" => "code"],
            ['id' => '101', 'title' => 'india', "code" => "code"],
            ['id' => '102', 'title' => 'indonesia', "code" => "code"],
            ['id' => '103', 'title' => 'iran', "code" => "code"],
            ['id' => '104', 'title' => 'iraq', "code" => "code"],
            ['id' => '105', 'title' => 'ireland', "code" => "code"],
            ['id' => '106', 'title' => 'israel', "code" => "code"],
            ['id' => '107', 'title' => 'italy', "code" => "code"],
            ['id' => '108', 'title' => 'jamaica', "code" => "code"],
            ['id' => '109', 'title' => 'japan', "code" => "code"],
            ['id' => '110', 'title' => 'jersey', "code" => "code"],
            ['id' => '111', 'title' => 'jordan', "code" => "code"],
            ['id' => '112', 'title' => 'kazakhstan', "code" => "code"],
            ['id' => '113', 'title' => 'kenya', "code" => "code"],
            ['id' => '114', 'title' => 'kiribati', "code" => "code"],
            ['id' => '115', 'title' => 'korea north', "code" => "code"],
            ['id' => '116', 'title' => 'korea south', "code" => "code"],
            ['id' => '117', 'title' => 'kuwait', "code" => "code"],
            ['id' => '118', 'title' => 'kyrgyzstan', "code" => "code"],
            ['id' => '119', 'title' => 'laos', "code" => "code"],
            ['id' => '120', 'title' => 'latvia', "code" => "code"],
            ['id' => '121', 'title' => 'lebanon', "code" => "code"],
            ['id' => '122', 'title' => 'lesotho', "code" => "code"],
            ['id' => '123', 'title' => 'liberia', "code" => "code"],
            ['id' => '124', 'title' => 'libya', "code" => "code"],
            ['id' => '125', 'title' => 'liechtenstein', "code" => "code"],
            ['id' => '126', 'title' => 'lithuania', "code" => "code"],
            ['id' => '127', 'title' => 'luxembourg', "code" => "code"],
            ['id' => '128', 'title' => 'macau s.a.r.', "code" => "code"],
            ['id' => '129', 'title' => 'macedonia', "code" => "code"],
            ['id' => '130', 'title' => 'madagascar', "code" => "code"],
            ['id' => '131', 'title' => 'malawi', "code" => "code"],
            ['id' => '132', 'title' => 'malaysia', "code" => "code"],
            ['id' => '133', 'title' => 'maldives', "code" => "code"],
            ['id' => '134', 'title' => 'mali', "code" => "code"],
            ['id' => '135', 'title' => 'malta', "code" => "code"],
            ['id' => '136', 'title' => 'man (isle of)', "code" => "code"],
            ['id' => '137', 'title' => 'marshall islands', "code" => "code"],
            ['id' => '138', 'title' => 'martinique', "code" => "code"],
            ['id' => '139', 'title' => 'mauritania', "code" => "code"],
            ['id' => '140', 'title' => 'mauritius', "code" => "code"],
            ['id' => '141', 'title' => 'mayotte', "code" => "code"],
            ['id' => '142', 'title' => 'mexico', "code" => "code"],
            ['id' => '143', 'title' => 'micronesia', "code" => "code"],
            ['id' => '144', 'title' => 'moldova', "code" => "code"],
            ['id' => '145', 'title' => 'monaco', "code" => "code"],
            ['id' => '146', 'title' => 'mongolia', "code" => "code"],
            ['id' => '147', 'title' => 'montserrat', "code" => "code"],
            ['id' => '148', 'title' => 'morocco', "code" => "code"],
            ['id' => '149', 'title' => 'mozambique', "code" => "code"],
            ['id' => '150', 'title' => 'myanmar', "code" => "code"],
            ['id' => '151', 'title' => 'namibia', "code" => "code"],
            ['id' => '152', 'title' => 'nauru', "code" => "code"],
            ['id' => '153', 'title' => 'nepal', "code" => "code"],
            ['id' => '154', 'title' => 'netherlands antilles', "code" => "code"],
            ['id' => '155', 'title' => 'netherlands the', "code" => "code"],
            ['id' => '156', 'title' => 'new caledonia', "code" => "code"],
            ['id' => '157', 'title' => 'new zealand', "code" => "code"],
            ['id' => '158', 'title' => 'nicaragua', "code" => "code"],
            ['id' => '159', 'title' => 'niger', "code" => "code"],
            ['id' => '160', 'title' => 'nigeria', "code" => "code"],
            ['id' => '161', 'title' => 'niue', "code" => "code"],
            ['id' => '162', 'title' => 'norfolk island', "code" => "code"],
            ['id' => '163', 'title' => 'northern mariana islands', "code" => "code"],
            ['id' => '164', 'title' => 'norway', "code" => "code"],
            ['id' => '165', 'title' => 'oman', "code" => "code"],
            ['id' => '166', 'title' => 'pakistan', "code" => "code"],
            ['id' => '167', 'title' => 'palau', "code" => "code"],
            ['id' => '168', 'title' => 'palestinian territory occupied', "code" => "code"],
            ['id' => '169', 'title' => 'panama', "code" => "code"],
            ['id' => '170', 'title' => 'papua new guinea', "code" => "code"],
            ['id' => '171', 'title' => 'paraguay', "code" => "code"],
            ['id' => '172', 'title' => 'peru', "code" => "code"],
            ['id' => '173', 'title' => 'philippines', "code" => "code"],
            ['id' => '174', 'title' => 'pitcairn island', "code" => "code"],
            ['id' => '175', 'title' => 'poland', "code" => "code"],
            ['id' => '176', 'title' => 'portugal', "code" => "code"],
            ['id' => '177', 'title' => 'puerto rico', "code" => "code"],
            ['id' => '178', 'title' => 'qatar', "code" => "code"],
            ['id' => '179', 'title' => 'reunion', "code" => "code"],
            ['id' => '180', 'title' => 'romania', "code" => "code"],
            ['id' => '181', 'title' => 'russia', "code" => "code"],
            ['id' => '182', 'title' => 'rwanda', "code" => "code"],
            ['id' => '183', 'title' => 'saint helena', "code" => "code"],
            ['id' => '184', 'title' => 'saint kitts and nevis', "code" => "code"],
            ['id' => '185', 'title' => 'saint lucia', "code" => "code"],
            ['id' => '186', 'title' => 'saint pierre and miquelon', "code" => "code"],
            ['id' => '187', 'title' => 'saint vincent and the grenadines', "code" => "code"],
            ['id' => '188', 'title' => 'samoa', "code" => "code"],
            ['id' => '189', 'title' => 'san marino', "code" => "code"],
            ['id' => '190', 'title' => 'sao tome and principe', "code" => "code"],
            ['id' => '191', 'title' => 'saudi arabia', "code" => "code"],
            ['id' => '192', 'title' => 'senegal', "code" => "code"],
            ['id' => '193', 'title' => 'serbia', "code" => "code"],
            ['id' => '194', 'title' => 'seychelles', "code" => "code"],
            ['id' => '195', 'title' => 'sierra leone', "code" => "code"],
            ['id' => '196', 'title' => 'singapore', "code" => "code"],
            ['id' => '197', 'title' => 'slovakia', "code" => "code"],
            ['id' => '198', 'title' => 'slovenia', "code" => "code"],
            ['id' => '199', 'title' => 'smaller territories of the uk', "code" => "code"],
            ['id' => '200', 'title' => 'solomon islands', "code" => "code"],
            ['id' => '201', 'title' => 'somalia', "code" => "code"],
            ['id' => '202', 'title' => 'south africa', "code" => "code"],
            ['id' => '203', 'title' => 'south georgia', "code" => "code"],
            ['id' => '204', 'title' => 'south sudan', "code" => "code"],
            ['id' => '205', 'title' => 'spain', "code" => "code"],
            ['id' => '206', 'title' => 'sri lanka', "code" => "code"],
            ['id' => '207', 'title' => 'sudan', "code" => "code"],
            ['id' => '208', 'title' => 'suriname', "code" => "code"],
            ['id' => '209', 'title' => 'svalbard and jan mayen islands', "code" => "code"],
            ['id' => '210', 'title' => 'swaziland', "code" => "code"],
            ['id' => '211', 'title' => 'sweden', "code" => "code"],
            ['id' => '212', 'title' => 'switzerland', "code" => "code"],
            ['id' => '213', 'title' => 'syria', "code" => "code"],
            ['id' => '214', 'title' => 'taiwan', "code" => "code"],
            ['id' => '215', 'title' => 'tajikistan', "code" => "code"],
            ['id' => '216', 'title' => 'tanzania', "code" => "code"],
            ['id' => '217', 'title' => 'thailand', "code" => "code"],
            ['id' => '218', 'title' => 'togo', "code" => "code"],
            ['id' => '219', 'title' => 'tokelau', "code" => "code"],
            ['id' => '220', 'title' => 'tonga', "code" => "code"],
            ['id' => '221', 'title' => 'trinidad and tobago', "code" => "code"],
            ['id' => '222', 'title' => 'tunisia', "code" => "code"],
            ['id' => '223', 'title' => 'turkey', "code" => "code"],
            ['id' => '224', 'title' => 'turkmenistan', "code" => "code"],
            ['id' => '225', 'title' => 'turks and caicos islands', "code" => "code"],
            ['id' => '226', 'title' => 'tuvalu', "code" => "code"],
            ['id' => '227', 'title' => 'uganda', "code" => "code"],
            ['id' => '228', 'title' => 'ukraine', "code" => "code"],
            ['id' => '229', 'title' => 'united arab emirates', "code" => "code"],
            ['id' => '230', 'title' => 'united kingdom', "code" => "code"],
            ['id' => '231', 'title' => 'united states', "code" => "code"],
            ['id' => '232', 'title' => 'united states minor outlying islands', "code" => "code"],
            ['id' => '233', 'title' => 'uruguay', "code" => "code"],
            ['id' => '234', 'title' => 'uzbekistan', "code" => "code"],
            ['id' => '235', 'title' => 'vanuatu', "code" => "code"],
            ['id' => '236', 'title' => 'vatican city state (holy see)', "code" => "code"],
            ['id' => '237', 'title' => 'venezuela', "code" => "code"],
            ['id' => '238', 'title' => 'vietnam', "code" => "code"],
            ['id' => '239', 'title' => 'virgin islands (british)', "code" => "code"],
            ['id' => '240', 'title' => 'virgin islands (us)', "code" => "code"],
            ['id' => '241', 'title' => 'wallis and futuna islands', "code" => "code"],
            ['id' => '242', 'title' => 'western sahara', "code" => "code"],
            ['id' => '243', 'title' => 'yemen', "code" => "code"],
            ['id' => '244', 'title' => 'yugoslavia', "code" => "code"],
            ['id' => '245', 'title' => 'zambia', "code" => "code"],
            ['id' => '246', 'title' => 'zimbabwe', "code" => "code"]
        ]);
    }
}
