<?php

namespace Database\Seeders\Address;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\District;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        return District::insert([
                // Ankara (city_id = 1)
                ['city_id' => 1, 'title' => 'akyurt'],
                ['city_id' => 1, 'title' => 'altindag'],
                ['city_id' => 1, 'title' => 'ayas'],
                ['city_id' => 1, 'title' => 'bala'],
                ['city_id' => 1, 'title' => 'beypazari'],
                ['city_id' => 1, 'title' => 'cankaya'],
                ['city_id' => 1, 'title' => 'cubuk'],
                ['city_id' => 1, 'title' => 'elmadag'],
                ['city_id' => 1, 'title' => 'etimesgut'],
                ['city_id' => 1, 'title' => 'evren'],
                ['city_id' => 1, 'title' => 'golbasi'],
                ['city_id' => 1, 'title' => 'gudul'],
                ['city_id' => 1, 'title' => 'haymana'],
                ['city_id' => 1, 'title' => 'kahramankazan'],
                ['city_id' => 1, 'title' => 'kecioren'],
                ['city_id' => 1, 'title' => 'kizilcahamam'],
                ['city_id' => 1, 'title' => 'mamak'],
                ['city_id' => 1, 'title' => 'nallihan'],
                ['city_id' => 1, 'title' => 'polatli'],
                ['city_id' => 1, 'title' => 'pursaklar'],
                ['city_id' => 1, 'title' => 'sincan'],
                ['city_id' => 1, 'title' => 'yenimahalle'],
                // Antalya (city_id = 2)
                ['city_id' => 2, 'title' => 'aksu'],
                ['city_id' => 2, 'title' => 'alanya'],
                ['city_id' => 2, 'title' => 'demre'],
                ['city_id' => 2, 'title' => 'dosemealti'],
                ['city_id' => 2, 'title' => 'finike'],
                ['city_id' => 2, 'title' => 'gazipasa'],
                ['city_id' => 2, 'title' => 'gundogmus'],
                ['city_id' => 2, 'title' => 'ibradi'],
                ['city_id' => 2, 'title' => 'kas'],
                ['city_id' => 2, 'title' => 'kemer'],
                ['city_id' => 2, 'title' => 'kepez'],
                ['city_id' => 2, 'title' => 'konyaalti'],
                ['city_id' => 2, 'title' => 'korkuteli'],
                ['city_id' => 2, 'title' => 'kumluca'],
                ['city_id' => 2, 'title' => 'manavgat'],
                ['city_id' => 2, 'title' => 'muratpasa'],
                ['city_id' => 2, 'title' => 'serik'],
                // Eskişehir (city_id = 3)
                ['city_id' => 3, 'title' => 'alpu'],
                ['city_id' => 3, 'title' => 'beylikova'],
                ['city_id' => 3, 'title' => 'cifteler'],
                ['city_id' => 3, 'title' => 'gunyuzu'],
                ['city_id' => 3, 'title' => 'han'],
                ['city_id' => 3, 'title' => 'inseonu'],
                ['city_id' => 3, 'title' => 'mahmudiye'],
                ['city_id' => 3, 'title' => 'mihalgazi'],
                ['city_id' => 3, 'title' => 'mihaliccik'],
                ['city_id' => 3, 'title' => 'odunpazari'],
                ['city_id' => 3, 'title' => 'saricakaya'],
                ['city_id' => 3, 'title' => 'seyitgazi'],
                ['city_id' => 3, 'title' => 'sivrihisar'],
                ['city_id' => 3, 'title' => 'tepebasi'],
                // İstanbul (city_id = 3)
                ['city_id' => 3, 'title' => 'adalar'],
                ['city_id' => 3, 'title' => 'arnavutkoy'],
                ['city_id' => 3, 'title' => 'atasehir'],
                ['city_id' => 3, 'title' => 'avcilar'],
                ['city_id' => 3, 'title' => 'bagcilar'],
                ['city_id' => 3, 'title' => 'bahcelievler'],
                ['city_id' => 3, 'title' => 'bakirkoy'],
                ['city_id' => 3, 'title' => 'basaksehir'],
                ['city_id' => 3, 'title' => 'bayrampasa'],
                ['city_id' => 3, 'title' => 'besiktas'],
                ['city_id' => 3, 'title' => 'beykoz'],
                ['city_id' => 3, 'title' => 'beylikduzu'],
                ['city_id' => 3, 'title' => 'beyoglu'],
                ['city_id' => 3, 'title' => 'buyukcekmece'],
                ['city_id' => 3, 'title' => 'catalca'],
                ['city_id' => 3, 'title' => 'cekmekoy'],
                ['city_id' => 3, 'title' => 'esenler'],
                ['city_id' => 3, 'title' => 'esenyurt'],
                ['city_id' => 3, 'title' => 'eyupsultan'],
                ['city_id' => 3, 'title' => 'fatih'],
                ['city_id' => 3, 'title' => 'gaziosmanpasa'],
                ['city_id' => 3, 'title' => 'gungoren'],
                ['city_id' => 3, 'title' => 'kadikoy'],
                ['city_id' => 3, 'title' => 'kagithane'],
                ['city_id' => 3, 'title' => 'kartal'],
                ['city_id' => 3, 'title' => 'kucukcekmece'],
                ['city_id' => 3, 'title' => 'maltepe'],
                ['city_id' => 3, 'title' => 'pendik'],
                ['city_id' => 3, 'title' => 'sancaktepe'],
                ['city_id' => 3, 'title' => 'sariyer'],
                ['city_id' => 3, 'title' => 'silivri'],
                ['city_id' => 3, 'title' => 'sultanbeyli'],
                ['city_id' => 3, 'title' => 'sultangazi'],
                ['city_id' => 3, 'title' => 'sile'],
                ['city_id' => 3, 'title' => 'sisli'],
                ['city_id' => 3, 'title' => 'tuzla'],
                ['city_id' => 3, 'title' => 'umraniye'],
                ['city_id' => 3, 'title' => 'uskudar'],
                ['city_id' => 3, 'title' => 'zeytinburnu'],
                // İzmir (city_id = 4)
                ['city_id' => 4, 'title' => 'aliaga'],
                ['city_id' => 4, 'title' => 'balcova'],
                ['city_id' => 4, 'title' => 'bayindir'],
                ['city_id' => 4, 'title' => 'bayrakli'],
                ['city_id' => 4, 'title' => 'bergama'],
                ['city_id' => 4, 'title' => 'beydag'],
                ['city_id' => 4, 'title' => 'bornova'],
                ['city_id' => 4, 'title' => 'buca'],
                ['city_id' => 4, 'title' => 'cesme'],
                ['city_id' => 4, 'title' => 'dikili'],
                ['city_id' => 4, 'title' => 'foca'],
                ['city_id' => 4, 'title' => 'gaziemir'],
                ['city_id' => 4, 'title' => 'guzelbahce'],
                ['city_id' => 4, 'title' => 'karabaglar'],
                ['city_id' => 4, 'title' => 'karaburun'],
                ['city_id' => 4, 'title' => 'karsiyaka'],
                ['city_id' => 4, 'title' => 'kemalpasa'],
                ['city_id' => 4, 'title' => 'kinik'],
                ['city_id' => 4, 'title' => 'konak'],
                ['city_id' => 4, 'title' => 'menderes'],
                ['city_id' => 4, 'title' => 'menemen'],
                ['city_id' => 4, 'title' => 'narlidere'],
                ['city_id' => 4, 'title' => 'odemis'],
                ['city_id' => 4, 'title' => 'seferihisar'],
                ['city_id' => 4, 'title' => 'selcuk'],
                ['city_id' => 4, 'title' => 'tire'],
                ['city_id' => 4, 'title' => 'torbali'],
                ['city_id' => 4, 'title' => 'urla'],
        ]);
    }
}
